// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfg7QrOsSJQWbuiNuTLS6EEr4b9QWUG8A',
    appId: '1:156341670248:web:afcc5bdf47a26756fd86dd',
    messagingSenderId: '156341670248',
    projectId: 'e-commerce-d945c',
    authDomain: 'e-commerce-d945c.firebaseapp.com',
    storageBucket: 'e-commerce-d945c.firebasestorage.app',
    measurementId: 'G-NG5RVV6LYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWphNKVxoEZBD45veONm-xABiANj_boBI',
    appId: '1:156341670248:android:b71cdba939505894fd86dd',
    messagingSenderId: '156341670248',
    projectId: 'e-commerce-d945c',
    storageBucket: 'e-commerce-d945c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamF0OWtCO54wlFd-wfc9U-0TIvjRniIg',
    appId: '1:156341670248:ios:5999e15f2bc351d2fd86dd',
    messagingSenderId: '156341670248',
    projectId: 'e-commerce-d945c',
    storageBucket: 'e-commerce-d945c.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamF0OWtCO54wlFd-wfc9U-0TIvjRniIg',
    appId: '1:156341670248:ios:5999e15f2bc351d2fd86dd',
    messagingSenderId: '156341670248',
    projectId: 'e-commerce-d945c',
    storageBucket: 'e-commerce-d945c.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfg7QrOsSJQWbuiNuTLS6EEr4b9QWUG8A',
    appId: '1:156341670248:web:1a66d136ea10c1f2fd86dd',
    messagingSenderId: '156341670248',
    projectId: 'e-commerce-d945c',
    authDomain: 'e-commerce-d945c.firebaseapp.com',
    storageBucket: 'e-commerce-d945c.firebasestorage.app',
    measurementId: 'G-57FGZ6M0TM',
  );
}
